### ISSUE TITLE
ArtemisTestResource.start results InvalidPathException for DEFAULT_CONFIGURATION_NAME

### ISSUE THREAD

**Issue by robert-istvan** [quarkiverse/quarkus-artemis#104]
Version 2.0.1 

`...
Caused by: java.nio.file.InvalidPathException: Illegal char <<> at index 17: ./target/artemis/<default>
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232)
	at java.base/java.nio.file.Path.of(Path.java:147)
	at java.base/java.nio.file.Paths.get(Paths.java:69)
	at io.quarkus.artemis.test.ArtemisTestResource.start(ArtemisTestResource.java:40)
	... 5 more`

**Comment by middagj** [comment]
@robert-istvan can you try a dev install?

**Comment by robert-istvan** [comment]
Hi @middagj,
he correction works for me now. Thank you,

**Comment by middagj** [comment]
We are releasing 2.0.2 now, should be available in an hour.

**Comment by turing85** [comment]
Version `2.0.2`to fix this bug has been released. It should be available via maven in the next few hours. Release notes are [here](https://github.com/quarkiverse/quarkus-artemis/releases/tag/2.0.2).
